config/routes.rb
Personalsite::Application.routes.draw do
  root to: 'high_voltage/pages#show', id: 'home'
  match '/games' => 'high_voltage/pages#show', as: :static, id: 'games_index'
  match '/resume' => 'high_voltage/pages#show', as: :static, id: 'resume'
  match '/resumes' => 'high_voltage/pages#show', as: :static, id: 'resume'
  match '/contact' => 'high_voltage/pages#show', as: :static, id: 'contact'

  match '/lightseeker' => 'high_voltage/pages#show', as: :static, id: 'lightseeker'
  match '/cat4' => 'high_voltage/pages#show', as: :static, id: 'cat4'
  match '/sectarian' => 'high_voltage/pages#show', as: :static, id: 'sectarian'
  match '/blowback' => 'high_voltage/pages#show', as: :static, id: 'blowback'
  match '/boundaries' => 'high_voltage/pages#show', as: :static, id: 'boundaries'
  match '/numbernommers' => 'high_voltage/pages#show', as: :static, id: 'numbernommers'
  match '/numbernommers2' => 'high_voltage/pages#show', as: :static, id: 'numbernommers2'
  match '/tat' => 'high_voltage/pages#show', as: :static, id: 'tat'
  match '/vengeance' => 'high_voltage/pages#show', as: :static, id: 'vengeance'
  match '/blowback/making_of' => 'high_voltage/pages#show', as: :static, id: 'making_of_blowback/1'
  match '/blowback/making_of/1' => 'high_voltage/pages#show', as: :static, id: 'making_of_blowback/1'
  match '/blowback/making_of/2' => 'high_voltage/pages#show', as: :static, id: 'making_of_blowback/2'
  match '/blowback/making_of/3' => 'high_voltage/pages#show', as: :static, id: 'making_of_blowback/3'
  match '/blowback/making_of/4' => 'high_voltage/pages#show', as: :static, id: 'making_of_blowback/4'
  match '/blowback/making_of/5' => 'high_voltage/pages#show', as: :static, id: 'making_of_blowback/5'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :message, :name

  #after_create :deliver_contact_notification

  def deliver_contact_notification
    ContactMailer.notify(self).deliver
    ContactMailer.contact(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  respond_to :html, :xml, :json
  make_resourceful do
    actions :new, :show
  end

  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save

        ContactMailer.notify(@contact).deliver
        ContactMailer.contact(@contact).deliver
        format.html { render action: 'show', notice: 'Thanks!  If you put in your email address correctly, you should be getting a confirmation shortly.
                    I usually send a real reply within 24 hours.'}
        #format.json {render json: {contact: @contact, created: true, html: render_to_string(partial: '/contacts/success',
        #                                                               layout: false, locals: {contact: @contact})}}
      else
        format.html { render action: "new" }
        #format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/deprecated_contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new()
  end

  def create
    @contact = Contact.new(params[:deprecated_contacts])
    if @contact.save
      respond_to do |format|
        format.html {render action: :new, notice: 'Thanks!  If you put in your email address correctly, you should be getting a confirmation shortly.
                    I usually send a real reply within 24 hours.!' }
        #format.json {render json: {deprecated_contacts: @contact, created: true, html: render_to_string(partial: '/contact/success',
        #                                                                               layout: false, locals: {deprecated_contacts: @contact})}}
      end
    else
      respond_to do |format|
        format.html {render action: :new, notice: 'There were some problems.  Try again?'}
        #format.json {render json: {deprecated_contacts: @contact, created: false, html: render_to_string(partial: 'contact/error',
        #                                                                                layout: false, locals: {deprecated_contacts: @contact})}}
      end
    end
  end

  def edit

  end

  def update
    @contact = Contact.new(params[:deprecated_contacts])
    if @contact.save
      respond_to do |format|
        format.html {render action: :new, notice: 'Thanks!  If you put in your email address correctly, you should be getting a confirmation shortly.
                    I usually send a real reply within 24 hours.!' }
        format.json {render json: {deprecated_contacts: @contact, created: true, html: render_to_string(partial: '/contact/success',
                                                                                             layout: false, locals: {deprecated_contacts: @contact})}}
      end
    else
      respond_to do |format|
        format.html {render action: :new, notice: 'There were some problems.  Try again?'}
        #format.json {render json: {deprecated_contacts: @contact, created: false, html: render_to_string(partial: 'contact/error',
        #                                                                                      layout: false, locals: {deprecated_contacts: @contact})}}
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_error.html.haml
.form_notice.error
  Something went wrong!  Try again?

app/views/contacts/_form.html.haml
#contact_form
  .header
    %h2
      Tell me
      %i exactly
      what you think
  .javascript_response

  = form_for @contact do |f|
    .name= f.text_field :name, :placeholder => 'Name (optional)'
    .email_address= f.text_field :email, :placeholder => 'Email Address (optional)'
    .message= f.text_area :message, placeholder: 'Your message here.'
    #contact_button= f.submit 'Send it away!', :id => 'sign_up'
#javascript_response

-#= form_for @contact do |f|
-#  -if @contact.errors.any?
-#    #error_explanation
-#      %h2= "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
-#      %ul
-#        - @contact.errors.full_messages.each do |msg|
-#          %li= msg
-#
-#  .field
-#    = f.label :email
-#    = f.text_field :email
-#  .field
-#    = f.label :name
-#    = f.text_field :name
-#  .field
-#    = f.label :message
-#    = f.text_area :message
-#  .actions
-#    = f.submit 'Save'

app/views/contacts/_success.haml
.form_notice
  Thanks!  If you put in your email address correctly, you should be getting a confirmation shortly.
  I usually send a real reply within 24 hours.

app/views/contacts/_success.html.haml
.form_notice
  Thanks!  If you put in your email address correctly, you should be getting a confirmation shortly.
  I usually send a real reply within 24 hours.

app/views/contacts/edit.html.haml
%h1 Editing contact

= render 'form'

= link_to 'Show', @contact
\|
= link_to 'Back', contacts_path

app/views/contacts/index.html.haml
%h1 Listing contacts

%table
  %tr
    %th Email
    %th Name
    %th Message
    %th
    %th
    %th

  - @contacts.each do |contact|
    %tr
      %td= contact.email
      %td= contact.name
      %td= contact.message
      %td= link_to 'Show', contact
      %td= link_to 'Edit', edit_contact_path(contact)
      %td= link_to 'Destroy', contact, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Contact', new_contact_path

app/views/contacts/new.html.haml
%h1 New contact

= render 'form'

= link_to 'Back', contacts_path

app/views/contacts/show.html.haml
%h3
  %i We got this.

%p
  You should be getting an automatic email at
  = @contact.email
  real soon, and a personal response within 24 hours.
%p Thanks!
%p= '--Jeffrey'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jeffrey Biles!</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-30302804-1']);
      _gaq.push(['_setDomainName', 'jeffreybiles.com']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
</head>
<body>

<div id="navbar">
    <a href="/">Home</a>
    <!-- <a href="/games">Games</a> -->
    <!-- <a href="http://blog.jeffreybiles.com">Blog</a> -->
    <!--<a href="https://github.com/jeffreybiles">GitHub</a>-->
    <!-- <a href="/publications">Publications</a> -->
    <!-- <a href="http://www.mathmonstersgame.com">Math Monsters</a> -->
    <a href="http://www.emberscreencasts.com">Ember Screencasts</a>
    <a href="https://www.emberschool.com/">EmberSchool</a>
    <a href="/resume">Resume</a>
    <a href="/contact">Contact</a>
</div>

<%= yield %>
<div id="clear"></div>
<div id="footer" class="center writing_container">Want to tell me something really short?  Find me <a href="https://twitter.com/JeffreyBiles">on twitter</a>.</div>
</body>
</html>

app/views/pages/contact.html.haml
.writing_container.center
  %h3
    %a(href="mailto:bilesjeffrey@gmail.com") Email Me
  %h3
    %a(href="http://www.linkedin.com/profile/view?id=191858664") Link Me In
  %h3
    %a(href="#there is not even an echo. Please try a different option.") Shout into the void